NumPy可以针对全局数组进行复杂计算而不需要写python

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [5]:
%time for _ in range(10):my_arr2 = my_arr * 2

Wall time: 32.6 ms


In [6]:
%time for _ in range(10):my_list2 = my_list * 2

Wall time: 179 ms


# NumPy ndarray：多维数组对象

ndarray是Python中一个快速、灵活的大型数据集容器

In [7]:
import numpy as np

In [8]:
data = np.random.randn(2, 3)

In [9]:
data

array([[-0.14821372, -0.06158594, -0.91985463],
       [ 0.65512097, -0.12380606,  0.34029792]])

In [10]:
data * 10

array([[-1.4821372 , -0.61585944, -9.19854631],
       [ 6.55120967, -1.23806059,  3.40297918]])

In [11]:
data + data

array([[-0.29642744, -0.12317189, -1.83970926],
       [ 1.31024193, -0.24761212,  0.68059584]])

### shape属性、dtype属性

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

*生成ndarray* 

### array函数

In [14]:
data1 = [6, 7.5, 8, 0, 1]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
arr2 = np.array(data2)

In [20]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
arr2.ndim  # arr2是二维数组

2

In [22]:
arr2.shape

(2, 4)

还有很多其他函数可以创建新数组

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2, 3, 2))  # empty可以创建一个没有初始化数值的数组

array([[[8.36473820e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.92966904e-033]],

       [[5.94625983e-091, 9.34861555e-067],
        [6.54423895e-043, 1.95179900e+160],
        [3.99910963e+252, 1.44002702e+160]]])

### arange函数

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

*ndarray的数据类型*

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [29]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

### astype方法

In [32]:
arr = np.arange(1, 6)

In [33]:
arr.dtype

dtype('int32')

In [34]:
float_arr = arr.astype(np.float64)

In [35]:
float_arr.dtype

dtype('float64')

_注意：用astype方法的时候注意float->int;string->int_

利用另一个数组的属性来改变这个数组的属性

In [36]:
int_arr = np.arange(10)

In [38]:
calibers = np.array([.22, .270, .357],dtype=np.float64)

In [39]:
int_arr.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

也可以用类型代码来传入数据类型

In [40]:
empty_uint32 = np.empty(8, dtype='u4')

In [41]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

*NumPy数组算术*

In [42]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [43]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [45]:
arr -arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [49]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [51]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [52]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [53]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

*基础索引与切片*

In [54]:
arr = np.arange(10)

In [55]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr[5]

5

In [57]:
arr[5: 8]

array([5, 6, 7])

In [58]:
arr[5: 8] = 12

In [59]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

_注意：数组的切片是原数组的视图_

In [60]:
arr_slice = arr[5: 8]

In [61]:
arr_slice

array([12, 12, 12])

In [62]:
arr_slice[1] = 12345

In [63]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [64]:
arr_slice[:] = 64

In [65]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [66]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [67]:
arr2d[2]

array([7, 8, 9])

In [68]:
arr2d[0][2]

3

In [69]:
arr2d[0, 2]

3

2 * 2 * 3的数组

In [2]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [3]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [4]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [8]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

### 布尔索引